/**
 * /api/signals — Read stored signals (fast, no computation)
 *
 * This endpoint reads pre-computed signals from the DB.
 * Signals are generated by /api/detect (cron every 12h).
 * Use this for the frontend to avoid re-running detection on every page load.
 *
 * Public endpoint (read-only, no secrets exposed).
 */
import { NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { checkRateLimit } from "@/lib/auth";

const VALID_STATUSES = ["SIGNAL", "INSIGHT", "ARCHIVED"];

export async function GET(request: Request) {
  // Rate limit public endpoint
  const rlErr = checkRateLimit(request);
  if (rlErr) return rlErr;

  const url = new URL(request.url);
  const limitRaw = parseInt(url.searchParams.get("limit") || "10");
  const limit = Math.max(1, Math.min(100, isNaN(limitRaw) ? 10 : limitRaw));
  const status = url.searchParams.get("status") || "SIGNAL";

  // Validate status against allowlist
  if (!VALID_STATUSES.includes(status)) {
    return NextResponse.json(
      { error: `Invalid status. Must be one of: ${VALID_STATUSES.join(", ")}` },
      { status: 400 },
    );
  }

  const sql = getDb();

  try {
    const rawSignals = await sql`
      SELECT id, pattern_type, claim_ids, score, title, summary, evidence, status, detected_at
      FROM signals
      WHERE status = ${status}
      ORDER BY detected_at ASC, score DESC
      LIMIT ${limit}
    `;

    // Transform: extract analysis from evidence JSONB to top-level
    const signals = rawSignals.map((s) => {
      let evidence: Record<string, unknown> = {};
      try {
        evidence = typeof s.evidence === "string" ? JSON.parse(s.evidence) : (s.evidence || {});
      } catch {
        evidence = {};
      }

      return {
        ...s,
        evidence: {
          claims: Array.isArray(evidence?.claims) ? evidence.claims : [],
          gap: evidence?.gap,
          delta: evidence?.delta,
          window_days: evidence?.window_days,
        },
        analysis: evidence?.analysis || null,
        pairs: Array.isArray(evidence?.claims) && evidence.claims[0]?.pair
          ? [evidence.claims[0].pair]
          : [],
      };
    });

    return NextResponse.json({
      signals,
      count: signals.length,
    });
  } catch (err) {
    console.error("Signals API error:", err);
    return NextResponse.json(
      { error: "Failed to fetch signals" },
      { status: 500 },
    );
  }
}
