/**
 * /api/signals — Read stored signals (fast, no computation)
 *
 * This endpoint reads pre-computed signals from the DB.
 * Signals are generated by /api/detect (cron every 12h).
 * Use this for the frontend to avoid re-running detection on every page load.
 */
import { NextResponse } from "next/server";
import { getDb } from "@/lib/db";

export async function GET(request: Request) {
  const url = new URL(request.url);
  const limit = parseInt(url.searchParams.get("limit") || "10");
  const status = url.searchParams.get("status") || "SIGNAL";

  const sql = getDb();

  try {
    const rawSignals = await sql`
      SELECT id, pattern_type, claim_ids, score, title, summary, evidence, status, detected_at
      FROM signals
      WHERE status = ${status}
      ORDER BY score DESC, detected_at DESC
      LIMIT ${limit}
    `;

    // Transform: extract analysis from evidence JSONB to top-level
    const signals = rawSignals.map((s) => {
      const evidence = typeof s.evidence === "string" ? JSON.parse(s.evidence) : s.evidence;
      return {
        ...s,
        evidence: {
          claims: evidence?.claims || [],
          gap: evidence?.gap,
          delta: evidence?.delta,
          window_days: evidence?.window_days,
        },
        analysis: evidence?.analysis || null,
        pairs: evidence?.claims?.[0]?.pair ? [evidence.claims[0].pair] : [],
      };
    });

    return NextResponse.json({
      signals,
      count: signals.length,
    });
  } catch (err) {
    return NextResponse.json(
      { error: (err as Error).message },
      { status: 500 },
    );
  }
}
